  CREATE TABLE "C##GYJ"."USERLIST" 
   (	"U_ID" NUMBER, 
	"U_PWD" VARCHAR2(20 BYTE), 
	"U_NAME" VARCHAR2(20 BYTE), 
	"U_PHONE" VARCHAR2(20 BYTE), 
	"U_ADDRESS" VARCHAR2(20 BYTE), 
	"U_GRADE" NUMBER, 
	"U_EMAIL" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("U_ID")


  CREATE TABLE "C##GYJ"."HOTEL" 
   (	"H_ID" NUMBER, 
	"H_NAME" VARCHAR2(20 BYTE), 
	"H_LOCATION" VARCHAR2(20 BYTE), 
	"H_XPOINT" NUMBER, 
	"H_YPOINT" NUMBER, 
	"H_TEL" VARCHAR2(20 BYTE), 
	"H_WIFI" NUMBER, 
	"H_PARKING" NUMBER, 
	"H_SWIMMING" NUMBER, 
	"H_ROOMSERVICE" NUMBER, 
	"H_BUS" NUMBER, 
	"H_GRADE" NUMBER, 
	"H_RATE" NUMBER, 
	"H_IMG" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("H_ID")


  CREATE TABLE "C##GYJ"."ROOM" 
   (	"R_ID" NUMBER, 
	"R_NAME" VARCHAR2(20 BYTE), 
	"H_ID" NUMBER, 
	"R_NO" VARCHAR2(20 BYTE), 
	"R_PEOPLE" NUMBER, 
	"R_TYPE" VARCHAR2(20 BYTE), 
	"R_COST" NUMBER, 
	"R_ABLE" NUMBER, 
	"R_BCOUNT" NUMBER, 
	"R_IMG1" VARCHAR2(50 BYTE), 
	"R_IMG2" VARCHAR2(50 BYTE), 
	"R_IMG3" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("R_ID")

  CREATE TABLE "C##GYJ"."BOOKING" 
   (	"B_NO" NUMBER, 
	"B_U_ID" NUMBER, 
	"B_H_ID" NUMBER, 
	"B_R_ID" NUMBER, 
	"B_CHECKIN" VARCHAR2(20 BYTE), 
	"B_CHECKOUT" VARCHAR2(20 BYTE), 
	"B_PEOPLE" NUMBER, 
	"B_DATE" VARCHAR2(20 BYTE), 
	"B_PLUS" NUMBER, 
	 PRIMARY KEY ("B_NO")


  CREATE TABLE "C##GYJ"."DASHBOARD" 
   (	"D_NO1" NUMBER, 
	"D_NO2" NUMBER, 
	"D_U_ID" NUMBER, 
	"D_H_ID" NUMBER, 
	"D_R_ID" NUMBER, 
	"D_B_NO" NUMBER, 
	"D_REP_LEV" NUMBER, 
	"D_AVAILABLE" NUMBER, 
	"D_SPOINT" NUMBER, 
	"D_TYTLE" VARCHAR2(50 BYTE), 
	"D_CONTENT" VARCHAR2(2048 BYTE), 
	"D_DATE" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("D_NO1", "D_NO2")

